name: tf-2.4.1n
channels:
  - conda-forge
dependencies:
  - python==3.8
  - pip
  - numpy==1.19.2
  - tensorflow-gpu==2.4.1
  - cudatoolkit=10.1
  - tensorflow-probability=0.7
  - matplotlib
  - imageio
  - jupyterlab
  - tqdm
  - pip:
    - tensorflow-addons
    - ipykernel